# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  futurabasura.com:
    site_hosts:
      - canonical: futurabasura.test
        redirects:
          - www.futurabasura.test
    local_path: ../site
    admin_email: admin@futurabasura.test
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
