# Created by trellis-cli v1.11.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  futurabasura.com:
    site_hosts:
      - canonical: futurabasura.test
        redirects:
          - www.futurabasura.test
    local_path: ../site
    admin_email: admin@futurabasura.test
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: manual
      cert: /Users/aitor/Documents/Sites/futurabasura.com/letsencrypt/futurabasura.test+5.pem
      key: /Users/aitor/Documents/Sites/futurabasura.com/letsencrypt/futurabasura.test+5-key.pem
    cache:
      enabled: false
