---
- name: Check if deploy_before scripts exist
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_before_paths
  loop: "{{ deploy_before | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_before_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-before

##################################################################
# Custom: Install GitHub deploy key to allow cloning via SSH
##################################################################

- name: Write GitHub deploy key from Vault
  copy:
    content: "{{ vault_github_deploy_key }}"
    dest: "/home/{{ web_user }}/.ssh/github_deploy_key"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "0600"

- name: Configure SSH to use GitHub deploy key
  copy:
    content: |
      Host github.com
        IdentityFile /home/{{ web_user }}/.ssh/github_deploy_key
        IdentitiesOnly yes
    dest: "/home/{{ web_user }}/.ssh/config"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "0644"

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ web_user }}/.ssh"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: "0700"

##################################################################

- import_tasks: initialize.yml
- import_tasks: update.yml
- import_tasks: prepare.yml
- import_tasks: build.yml
- import_tasks: share.yml
- import_tasks: finalize.yml

- name: Check if deploy_after scripts exist
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_after_paths
  loop: "{{ deploy_after | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_after_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-after
