# Created by trellis-cli v1.11.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  stage-futurabasura.com:
    site_hosts:
      - canonical: stage-futurabasura.com
    local_path: ../site
    branch: main
    repo: git@github.com:aitormendez/futurabasura.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
