# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  stage.futurabasura.com:
    site_hosts:
      - canonical: stage.futurabasura.com
    local_path: ../site
    branch: main
    repo: git@github.com:aitormendez/futurabasura.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    xmlrpc:
      enabled: false
