name: 🚀 Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Trellis CLI
        uses: roots/setup-trellis-cli@v1
        with:
          ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Sage 11 Theme
        run: |
          cd site/web/app/themes/sage
          corepack enable
          yarn
          yarn build

      - name: Build FB Blocks Plugin
        run: |
          cd site/web/app/plugins/fb-blocks
          yarn
          yarn build

      - name: Deploy to staging
        run: trellis deploy staging
