name: 🚀 Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install SSH key and known_hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Setup Trellis CLI
        uses: roots/setup-trellis-cli@v1
        with:
          ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Sage 11 Theme
        run: |
          cd site/web/app/themes/sage
          npm install
          npm run build

      - name: Build FB Blocks Plugin
        run: |
          cd site/web/app/plugins/fb-blocks
          npm install
          npm run build

      - name: Deploy to production
        run: trellis deploy production
