- name: Check for manifest
  stat:
    path: "{{ project_local_path }}/web/app/themes/sage/public/build/manifest.json"
  delegate_to: localhost
  register: entrypoints_data

- name: Entrypoints missing
  ansible.builtin.fail:
    msg: "The theme is missing the build manifest file"
  when: not entrypoints_data.stat.exists

- name: Copy production assets
  synchronize:
    src: "{{ project_local_path }}/web/app/themes/sage/public"
    dest: "{{ deploy_helper.new_release_path }}/web/app/themes/sage"
    group: no
    owner: no
    rsync_opts:
      - --exclude=hot
      - --chmod=Du=rwx
      - --chmod=Dg=rx
      - --chmod=Do=rx
      - --chmod=Fu=rw
      - --chmod=Fg=r
      - --chmod=Fo=r
  delegate_to: localhost

- name: Copy Sage vendor directory (PHP dependencies)
  synchronize:
    src: "{{ project_local_path }}/web/app/themes/sage/vendor"
    dest: "{{ deploy_helper.new_release_path }}/web/app/themes/sage"
    recursive: yes
    delete: yes
  delegate_to: localhost

- name: Copy Git submodules (fb-blocks)
  synchronize:
    src: "{{ project_local_path }}/web/app/plugins/fb-blocks/"
    dest: "{{ deploy_helper.new_release_path }}/web/app/plugins/"
    recursive: yes
    delete: yes
  delegate_to: localhost
